from sqlalchemy import Column, String, Integer, Float, Boolean, DateTime
from app.core.database import Base


class Transaction(Base):
    __tablename__ = "transactions"

    transaction_id = Column(String, primary_key=True, index=True)
    timestamp = Column(DateTime)  
    user_id = Column(String)
    account_age_days = Column(Integer)
    customer_tier = Column(String)
    kyc_level = Column(String)
    has_multiple_accounts = Column(Boolean)
    linked_card_count = Column(Integer)
    transaction_amount = Column(Float)
    transaction_currency = Column(String)
    transaction_type = Column(String)
    merchant_category = Column(String)
    merchant_id = Column(String)
    merchant_risk_score = Column(Float)
    transaction_hour = Column(Integer)
    transaction_day_of_week = Column(Integer)
    is_weekend_transaction = Column(Boolean)
    is_nighttime_transaction = Column(Boolean)
    device_id = Column(String)
    device_os = Column(String)
    device_type = Column(String)
    is_vpn_used = Column(Boolean)
    is_proxy_used = Column(Boolean)
    ip_address = Column(String)
    ip_risk_score = Column(Float)
    location_country = Column(String)
    location_city = Column(String)
    is_new_device = Column(Boolean)
    is_new_location = Column(Boolean)
    num_failed_attempts_24h = Column(Integer)
    prev_avg_txn_amount = Column(Float)
    txn_amount_deviation = Column(Float)
    daily_avg_spend = Column(Float)
    total_spend_last_7d = Column(Float)
    transaction_recency = Column(Float)
    txn_velocity_1h = Column(Float)
    txn_velocity_24h = Column(Float)
    transaction_success_rate_24h = Column(Float)
    has_multiple_devices = Column(Boolean)
    is_blacklisted_card = Column(Boolean)
    is_blacklisted_device = Column(Boolean)
    is_high_risk_country = Column(Boolean)
    distance_from_last_transaction = Column(Float)
    has_chargeback_history = Column(Boolean)
    previous_fraudulent_activity = Column(Boolean)
    account_fraud_reported = Column(Boolean)
    is_high_risk_behavior = Column(Boolean)
    label = Column(Float)

