version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env 
    environment:
      - DATABASE_URL=${DATABASE_URL}
    # Local db vol
    # environment:
    #   - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    volumes:
      - ./app:/app/app
      - ./alembic:/app/alembic
      - ./alembic.ini:/app/alembic.ini
      # - ./main.py:/app/main.py 
    command: >
      sh -c "python run_migrations.py && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    # depends_on:
    #   - db
    restart: unless-stopped


  # Local db vol
#   db:
#     image: postgres:15
#     env_file:
#       - .env
#     environment:
#       - POSTGRES_DB=${POSTGRES_DB}
#       - POSTGRES_USER=${POSTGRES_USER}
#       - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
#     ports:
#       - "5433:5432"
#     volumes:
#       - postgres_data:/var/lib/postgresql/data
#     restart: unless-stopped

# volumes:
#   postgres_data:



