"""added uploadhistory table

Revision ID: 3c51697bc11e
Revises: cf56a9f56213
Create Date: 2025-08-29 13:16:39.176243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c51697bc11e'
down_revision: Union[str, Sequence[str], None] = 'cf56a9f56213'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('upload_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('upload_id', sa.String(length=36), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('rows_processed', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_upload_history_id'), 'upload_history', ['id'], unique=False)
    op.create_index(op.f('ix_upload_history_upload_id'), 'upload_history', ['upload_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_upload_history_upload_id'), table_name='upload_history')
    op.drop_index(op.f('ix_upload_history_id'), table_name='upload_history')
    op.drop_table('upload_history')
    # ### end Alembic commands ###
